language: java

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11

script: mvn clean install -Dmaven.test.failure.ignore=true -Dproject.build.sourceEncoding=UTF-8 -Djunit5.excludeGroups=webservice,mysql

##services:
##  - mysql
##
##before_install:
## - mysql < mysqlConfig.sql  

after_success:
  - bash <(curl -s https://codecov.io/bash)
